version: "3"

services:
    app:
        image: golang:1.6.1-alpine
        volumes:
            - .:/go/src/github.com/amandhora/cache-proxy
        working_dir: /go/src/github.com/amandhora/cache-proxy
        command: go test -v
        links:
            - redis
        environment:
            REDIS_URL: redis:6379

    redis:
        image: redis:alpine




