version: "3"

services:
    test:
        image: golang:latest
        volumes:
            - ./http_test:/go/src/github.com/amandhora/cache-proxy/http_test
        working_dir: /go/src/github.com/amandhora/cache-proxy/http_test
        command: go run main.go
        depends_on:
            - proxy
        environment:
            PROXY_URL: proxy:8080
    proxy:
        build: .
        volumes:
            - .:/go/src/github.com/amandhora/cache-proxy
        working_dir: /go/src/github.com/amandhora/cache-proxy
        command: cache-proxy
        ports:
            - "8080:8080"
        depends_on:
            - redis
        environment:
            REDIS_URL: redis:6379
            PROXY_PORT: 8080
            CACHE_CAP: 1000
            CACHE_TTL_SEC: 600

    redis:
        image: redis:alpine
        volumes:
            - ./redis-data:/data
